config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: %i[create destroy]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: %i[create destroy]
  resources :users, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  validates :name, :ticker, presence: true
  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: 'Tpk_772a6fcd897b4eac800879b3c2991f4a',
      # publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      secret_token: 'Tsk_ed169eb46ca5462092d101b53f8edec7',
      endpoint: 'https://sandbox.iexapis.com/stable'
    )
    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue StandardError => exception
      nil
    end

  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name

    'Anonymous'
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back

    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == id }
  end

  def not_friends_with?(id_of_friend)
    !friends.where(id: id_of_friend).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/results' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = 'Please enter a valid symbol to search'
          format.js { render partial: 'users/results' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter a symbol to search'
        format.js { render partial: 'users/results' }
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio"
    redirect_to my_portfolio_path

  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} was successfully removed from portfolio"
    redirect_to my_portfolio_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/friends/_list.html.erb
<table class="table table-hover mt-3 w-100">
  <thead>
  <tr>
    <th>Email</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <% @friends.each do |friend| %>
    <tr>
      <td><%=  friend.email  %></td>
      <td><%= friend.first_name %></td>
      <td><%=  friend.last_name  %></td>
      <td>  <%= link_to 'View Profile', user_path(friend), class:  'btn btn-success btn-sm'  %>
        <%= link_to 'Unfollow',friendship_path(friend),method: :delete, data: {confirm: 'Are you sure you want to unfollow'},
                       class: 'btn btn-sm btn-danger'  %> </td>
    </tr>
  <%  end  %>

  </tbody>
</table>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong><%= notice %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong><%= alert %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>

<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= fa_icon 'user' %>
          <%= current_user.full_name %>
        </li>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/_navigation.html.erb
<div class="sidebar">
  <div class="brand">Finance Tracker</div>
  <div class="text-center">
    <%= fa_icon 'user' %>
    <%= current_user.full_name %>
  </div>
  <div class="brandline"></div>
  <nav>
    <ul>
      <li class="<%= 'active' if request.path == root_path %>">  <%= link_to 'Home',root_path %></li>
      <li class="<%= 'active' if request.path == my_portfolio_path %>">   <%= link_to 'Portfolio',my_portfolio_path %></li>
      <li class="<%= 'active' if request.path == edit_user_registration_path %>"> <%= link_to 'Edit Profile', edit_user_registration_path %> </li>
      <li  class="<%= 'active' if request.path == my_friends_path %>"> <%= link_to 'My Friends', my_friends_path %> </li>
      <li> <%= link_to 'Log out',destroy_user_session_path, method: :delete %> </li>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' if user_signed_in? %>
  <div class="container">
    <%#= render 'layouts/navbar' if user_signed_in? %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
<!-- <div>-->


<!-- </div>-->

  </body>
</html>

app/views/stocks/_list.html.erb
<table class="table table-hover mt-3 w-100">
  <thead>
  <tr>
    <th>Ticker</th>
    <th>Name</th>
    <th>Price</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <% @tracked_stocks.each do |stock| %>
    <tr>
      <td><%=  stock.ticker  %></td>
      <td><%= stock.name %></td>
      <td><%=  stock.last_price  %></td>
      <td>
        <% if current_user.can_track_stock?(stock.ticker) %>
          <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock.ticker),
                      class: 'btn btn-success btn-sm float-end', method: :post %>
        <% elsif current_user.id != @user.id %>
        <span class="text-muted fw-light">
          You are already tracking
          <% unless current_user.under_stock_limit? %>
           10 stocks
          <%  end %>
          <% if current_user.stock_already_tracked?(stock.ticker) %>
          this stock
          <% end %>
        </span>
        <% end %>
        <% if current_user.id == @user.id %>
        <%= link_to 'Remove',user_stock_path(stock),method: :delete, data: {confirm: 'Are you sure you want to delete'},
                       class: 'btn btn-sm btn-danger'  %>
          <% end %>
          </td>
    </tr>
  <%  end  %>

  </tbody>
</table>

app/views/users/_friend_result.html.erb
<div class="d-inline-block w-75 mt-2">
  <%= render 'layouts/messages' %>
</div>

<% if @friends %>
  <div class="card card-header d-inline-block w-100">
    <table class="table">
      <tbody>
      <% @friends.each do |friend| %>
        <tr>
         <td> <strong >Name: </strong> <span class="fw-light"><%= friend.full_name %></span> </td>
         <td> <strong >Email: </strong> <span class="fw-light"> <%= friend.email %> </span></td>
         <td colspan="2">  <%= link_to 'View Profile', user_path(friend), class:  'btn btn-success btn-sm'  %>
           <% if current_user.not_friends_with?(friend) %>
          <%= link_to 'Follow', friendships_path(friend: friend),
                      class: 'btn btn-info btn-sm', method: :post %>
             <% else %>
           <span class="text-muted fs-6 fw-light">Following</span>
           <% end %>
         </td>
        </tr>
      <% end %>

      </tbody>
    </table>


  </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/friend_result.html' %>'

app/views/users/_results.html.erb
<div class="d-inline-block w-100">
  <%= render 'layouts/messages' %>
</div>
<% if @stock %>
  <div class="card card-header d-inline-block w-100 mt-3">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Last Price: </strong> <%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
    <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker),
                                    class: 'btn btn-success btn-sm float-end', method: :post %>
      <% else %>
    <span class="badge bg-secondary">
      You are already tracking
      <% unless current_user.under_stock_limit? %>
       10 stocks
      <%  end %>
      <% if current_user.stock_already_tracked?(@stock.ticker) %>
      this stock
      <% end %>
    </span>
    <% end %>
  </div>
<% end %>

app/views/users/_results.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/results.html' %>'

app/views/users/my_friends.html.erb
<div class="w-75 mx-5  bg-white p-3 mt-5 pb-2">
  <h3 class="text-center"> <%= fa_icon 'users' %> My Friends</h3>
  <div class="search-area mt-4">
    <%= form_tag search_friend_path, remote: true, method: :get do %>
      <div class="form-group row ">
        <div class="col-sm-9 no-right-padding">
          <%= text_field_tag :friend, params[:friend],
                             placeholder: 'Search friends by name or email...',
                             autofocus: true,
                             class: 'form-control form-control-lg input-search' %>
        </div>
        <div class="col-sm-3 no-left-padding">
          <%= button_tag type: :submit, class: 'btn btn-success btn-search' do %>
            <%= fa_icon "search 2x"%>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div id="results"></div>
  <% unless @friends.empty? %>
    <%= render 'friends/list' %>
  <%  end %>
</div>

app/views/users/show.html.erb
<div class="w-75 mx-5  bg-white p-3 mt-5 pb-2">
 <h3 class="text-center"><%= @user.full_name %></h3>
  <div>
    <div>
      <table class="table table-bordered">
        <tr>
          <th>First Name</th>
          <td><%= @user.first_name %></td>
        </tr>
        <tr>
          <th>Last Name</th>
          <td><%= @user.last_name %></td>
        </tr>
        <tr>
          <th>Email</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th>Date Joined</th>
          <td><%= time_ago_in_words(@user.created_at) + ' ago' %></td>
        </tr>
        <tr>
          <th>Following</th>
          <td><%= @user.friends.count %></td>
        </tr>
        <tr>
          <th>Tracking</th>
          <td><%= "#{@user.stocks.count} stocks" %>  <button type="button" class="btn btn-primary btn-sm float-end" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            View Stocks
          </button> </td>

        </tr>
        <tr>
          <th>Status</th>
          <td>
            <% if current_user.not_friends_with?(@user) %>
              <%= link_to 'Follow', friendships_path(friend: @user),
                          class: 'btn btn-info btn-sm', method: :post %>
            <% else %>
              <span class="text-muted fs-6 fw-light">Following</span>
            <% end %>
          </td>
        </tr>
      </table>
      <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="staticBackdropLabel">Stocks</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <% unless @tracked_stocks.empty? %>
                <%=  render 'stocks/list'  %>
              <% end %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="w-75 h-75 mx-5  bg-white p-3 mt-5">
  <h1>Welcome to the finance tracker app</h1>

  <%#= link_to 'Log out',destroy_user_session_path, method: :delete %>

</div>